apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: grafana-certificate
spec:
  secretName: grafana-certificate
  duration: 8760h0m0s # 1 year
  renewBefore: 720h0m0s # 30 days
  commonName: grafana.upikoth.dev
  dnsNames:
    - grafana.upikoth.dev
  issuerRef:
    name: selfsigned-issuer
    kind: ClusterIssuer
