apiVersion: v1
kind: Service
metadata:
  name: grafana
spec:
  ports:
    - port: 4444
      protocol: TCP
      name: http
      targetPort: 3000
  selector:
    app: grafana
  sessionAffinity: None
