apiVersion: v1
kind: ConfigMap
metadata:
  name: alloy-config
data:
  config.yaml: |
    server:
      http_listen_port: 3100
      http_listen_address: 0.0.0.0
      grpc_listen_port: 0
      grpc_listen_address: 0.0.0.0

    metrics:
      configs:
        - name: integrations
          scrape_configs:
            - job_name: kubernetes-pods
              kubernetes_sd_configs:
                - role: pod
              relabel_configs:
                - source_labels:
                    - __meta_kubernetes_pod_label_app_kubernetes_io_name
                  target_label: app
                - source_labels:
                    - __meta_kubernetes_pod_node_name
                  target_label: node
                - source_labels:
                    - __meta_kubernetes_pod_name
                  target_label: pod
                - source_labels:
                    - __meta_kubernetes_pod_container_name
                  target_label: container
                - source_labels:
                    - __meta_kubernetes_namespace
                  target_label: namespace
                - action: replace
                  target_label: job
                  replacement: kubernetes-pods
                - action: replace
                  source_labels:
                    - __meta_kubernetes_pod_uid
                    - __meta_kubernetes_pod_container_name
                  target_label: __path__
                  separator: /
                  replacement: /var/log/pods/$1/*/$2/*.log
                - action: keep
                  source_labels:
                    - __path__
                  regex: .+
    logs:
      configs:
        - name: kubernetes-logs
          positions:
            filename: /tmp/positions.yaml
          scrape_configs:
            - job_name: kubernetes-pods-name
              kubernetes_sd_configs:
                - role: pod
              relabel_configs:
                - source_labels:
                    - __meta_kubernetes_pod_label_app_kubernetes_io_name
                  target_label: app
                - source_labels:
                    - __meta_kubernetes_pod_node_name
                  target_label: node
                - source_labels:
                    - __meta_kubernetes_pod_name
                  target_label: pod
                - source_labels:
                    - __meta_kubernetes_pod_container_name
                  target_label: container
                - source_labels:
                    - __meta_kubernetes_namespace
                  target_label: namespace
                - action: replace
                  target_label: job
                  replacement: kubernetes-pods-name
                - action: replace
                  source_labels:
                    - __meta_kubernetes_pod_uid
                    - __meta_kubernetes_pod_container_name
                  target_label: __path__
                  separator: /
                  replacement: /var/log/pods/$1/*/$2/*.log
                - action: keep
                  source_labels:
                    - __path__
                  regex: .+
              pipeline_stages:
                - docker: {}
          clients:
            - url: http://loki:3100/loki/api/v1/push
              batchwait: 1s
              batchsize: 1024
              timeout: 10s
              backoff_config:
                min_period: 1s
                max_period: 5s
