apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring

resources:
  - loki-config.yaml
  - loki-statefulset.yaml
  - loki-service.yaml
  - promtail-config.yaml
  - promtail-daemonset.yaml
  - promtail-serviceaccount.yaml

commonLabels:
  app.kubernetes.io/part-of: observability
  app.kubernetes.io/component: logging
  app.kubernetes.io/name: loki-stack
  app.kubernetes.io/instance: loki-stack
  app.kubernetes.io/managed-by: kustomize
