apiVersion: v1
kind: ConfigMap
metadata:
  name: loki-config
data:
  loki.yaml: |
    auth_enabled: false
    server:
      http_listen_port: 3100
    ingester:
      lifecycler:
        address: 127.0.0.1
        ring:
          kvstore:
            store: inmemory
          replication_factor: 1
        final_sleep: 0s
      chunk_idle_period: 5m
      chunk_retain_period: 30s
    schema_config:
      configs:
        - from: 2020-05-15
          store: boltdb
          object_store: filesystem
          schema: v11
          index:
            prefix: index_
            period: 24h
    storage_config:
      boltdb:
        directory: /data/loki/index
      filesystem:
        directory: /data/loki/chunks
      engine: filesystem
      filesystem:
        directory: /data/loki/chunks
      boltdb:
        directory: /data/loki/index
      cache:
        enable_fifocache: true
        validity: 24h
        default_validity: 12h
        background: true
        max_size_items: 2048
        ttl: 24h
      index:
        prefix: index_
        period: 24h
      chunks:
        prefix: chunks_
        period: 24h
      retention:
        enabled: true
        delete_delay: 2h
        working_directory: /data/loki/retention
        delete_worker_count: 150
        max_entries: 2000000
        target_size_bytes: 17179869184  # 16GB
        max_size_bytes: 19327352832     # 18GB
    limits_config:
      enforce_metric_name: false
      reject_old_samples: true
      reject_old_samples_max_age: 168h
      ingestion_rate_mb: 10
      ingestion_burst_size_mb: 20
      max_global_streams_per_user: 10000
      max_line_size: 2MB
      per_stream_rate_limit: 5MB
      per_stream_rate_limit_burst: 10MB
    chunk_store_config:
      max_look_back_period: 0s
    table_manager:
      retention_deletes_enabled: true
      retention_period: 0s
    compactor:
      working_directory: /data/loki/compactor
      shared_store: filesystem
      compaction_interval: 10m
      retention_enabled: true
      retention_delete_delay: 2h
      retention_delete_worker_count: 150
