apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-state-metrics-deployment
  labels:
    app.kubernetes.io/name: kube-state-metrics
    app.kubernetes.io/version: v2.9.2
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: kube-state-metrics
  template:
    metadata:
      labels:
        app.kubernetes.io/name: kube-state-metrics
    spec:
      serviceAccountName: kube-state-metrics-service-account
      containers:
        - name: kube-state-metrics-container
          image: registry.k8s.io/kube-state-metrics/kube-state-metrics:v2.9.2
          args:
            - --host=0.0.0.0
            - --port=8080
            - --telemetry-port=8081
            - --metric-labels-allowlist=deployments=[*]
            - --metric-labels-allowlist=nodes=[*]
            - --metric-labels-allowlist=pods=[*]
            - --metric-labels-allowlist=services=[*]
            - --metric-labels-allowlist=containers=[*]
            - --metric-labels-allowlist=persistentvolumeclaims=[*]
            - --metric-labels-allowlist=persistentvolumes=[*]
            - --metric-labels-allowlist=configmaps=[*]
            - --metric-labels-allowlist=secrets=[*]
            - --metric-labels-allowlist=namespaces=[*]
            - --metric-labels-allowlist=resourcequotas=[*]
            - --metric-labels-allowlist=replicationcontrollers=[*]
            - --metric-labels-allowlist=limitranges=[*]
            - --metric-labels-allowlist=endpoints=[*]
            - --metric-labels-allowlist=statefulsets=[*]
            - --metric-labels-allowlist=daemonsets=[*]
            - --metric-labels-allowlist=jobs=[*]
            - --metric-labels-allowlist=cronjobs=[*]
            - --metric-labels-allowlist=horizontalpodautoscalers=[*]
            - --metric-labels-allowlist=poddisruptionbudgets=[*]
            - --metric-labels-allowlist=certificatesigningrequests=[*]
            - --metric-labels-allowlist=storageclasses=[*]
            - --metric-labels-allowlist=volumeattachments=[*]
            - --metric-labels-allowlist=mutatingwebhookconfigurations=[*]
            - --metric-labels-allowlist=validatingwebhookconfigurations=[*]
            - --metric-labels-allowlist=networkpolicies=[*]
            - --metric-labels-allowlist=ingresses=[*]
            - --metric-labels-allowlist=leases=[*]
          ports:
            - name: http-metrics
              containerPort: 8080
            - name: telemetry
              containerPort: 8081
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 5
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 5
            timeoutSeconds: 5
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 200m
              memory: 256Mi
