apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kube-state-metrics

resources:
  - deployment.yaml
  - service.yaml
  - serviceaccount.yaml
  - clusterrole.yaml
  - clusterrolebinding.yaml
