apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - daemonset.yaml
  - service.yaml

commonLabels:
  app.kubernetes.io/part-of: observability
  app.kubernetes.io/name: node-exporter
  app.kubernetes.io/managed-by: kustomize
