apiVersion: v1
kind: Service
metadata:
  name: node-exporter-service
  labels:
    app.kubernetes.io/name: node-exporter
spec:
  ports:
    - port: 9100
      targetPort: 9100
      protocol: TCP
      name: metrics
  selector:
    app.kubernetes.io/name: node-exporter
