apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: loki

resources:
  - loki-config.yaml
  - loki-statefulset.yaml
  - loki-service.yaml

commonLabels:
  app.kubernetes.io/part-of: observability
  app.kubernetes.io/name: loki
  app.kubernetes.io/managed-by: kustomize
