apiVersion: v1
kind: ConfigMap
metadata:
  name: loki-config
data:
  loki.yaml: |
    auth_enabled: false

    server:
      http_listen_port: 3100

    common:
      path_prefix: /data/loki
      replication_factor: 1
      ring:
        instance_addr: ${POD_IP}
        kvstore:
          store: memberlist

    schema_config:
      configs:
      - from: "2020-05-15"
        store: tsdb
        object_store: filesystem
        schema: v13
        index:
          prefix: index_
          period: 24h

    storage_config:
      filesystem:
        directory: /data/loki/chunks

    ingester:
      chunk_idle_period: 3m
      chunk_target_size: 1536000 # 1.5MB
      chunk_retain_period: 1m
      wal:
        enabled: true
        dir: /data/loki/wal

    compactor:
      working_directory: /data/loki/compactor
      compaction_interval: 10m
      retention_enabled: true
      retention_delete_delay: 2h

    limits_config:
      ingestion_rate_mb: 15
      ingestion_burst_size_mb: 30
      max_streams_per_user: 10000
      max_global_streams_per_user: 20000
