apiVersion: grafana.integreatly.org/v1beta1
kind: Grafana
metadata:
  name: grafana
  labels:
    app: grafana
spec:
  config:
    log:
      mode: "console"
    auth:
      disable_login_form: "true"
      disable_signout_menu: "true"
      disable_signout_button: "true"
      anonymous:
        enabled: "true"
