apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: grafana

resources:
  - grafana.yaml
  - service.yaml
  - ingress-http.yaml
  - ingress-https.yaml
  - certificate.yaml
  - dashboards.yaml
  - datasources.yaml

commonLabels:
  app.kubernetes.io/part-of: observability
  app.kubernetes.io/name: grafana
  app.kubernetes.io/managed-by: kustomize
