apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: grafana
    app.kubernetes.io/part-of: observability
    argocd.argoproj.io/instance: grafana
  name: grafana-service
  namespace: grafana
spec:
  ports:
    - name: http
      port: 4444
      protocol: TCP
      targetPort: 3000
  selector:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: grafana
    app.kubernetes.io/part-of: observability
  sessionAffinity: None
