apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - configmap.yaml
  - deployment.yaml
  - service.yaml
  - pvc.yaml

commonLabels:
  app.kubernetes.io/part-of: observability
  app.kubernetes.io/name: prometheus
  app.kubernetes.io/managed-by: kustomize
