apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: certificate-tls
spec:
  secretName: certificate-tls
  duration: 8760h0m0s
  renewBefore: 720h0m0s
  commonName: argocd.upikoth.dev
  dnsNames:
    - argocd.upikoth.dev
  issuerRef:
    name: selfsigned-issuer
    kind: ClusterIssuer
