apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-tls
  namespace: cert-manager
spec:
  secretName: wildcard-tls
  duration: 8760h0m0s
  renewBefore: 720h0m0s
  dnsNames:
    - "*.upikoth.dev"
  issuerRef:
    name: selfsigned-issuer
    kind: ClusterIssuer
