apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: argocd-server
  labels:
    app.kubernetes.io/component: server
    app.kubernetes.io/instance: argocd
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: argocd-server
    app.kubernetes.io/part-of: argocd
    app.kubernetes.io/version: v2.14.3
    helm.sh/chart: argo-cd-7.8.7
  annotations:
    meta.helm.sh/release-name: argocd
    meta.helm.sh/release-namespace: argocd
  selfLink: /apis/rbac.authorization.k8s.io/v1/clusterroles/argocd-server
spec: {}
rules:
  - verbs:
      - delete
      - get
      - patch
    apiGroups:
      - "*"
    resources:
      - "*"
  - verbs:
      - list
      - create
    apiGroups:
      - ""
    resources:
      - events
      - pods/exec
  - verbs:
      - get
    apiGroups:
      - ""
    resources:
      - pods
      - pods/log
  - verbs:
      - get
      - list
      - update
      - watch
    apiGroups:
      - argoproj.io
    resources:
      - applications
      - applicationsets
  - verbs:
      - create
    apiGroups:
      - batch
    resources:
      - jobs
  - verbs:
      - create
    apiGroups:
      - argoproj.io
    resources:
      - workflows
