apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
labels:
  app.kubernetes.io/instance: argocd
  app.kubernetes.io/managed-by: Helm
  app.kubernetes.io/name: argocd-cm
  app.kubernetes.io/part-of: argocd
data:
  admin.enabled: "true"
  application.instanceLabelKey: argocd.argoproj.io/instance
  application.sync.impersonation.enabled: "false"
  exec.enabled: "false"
  server.rbac.log.enforce.enable: "false"
  statusbadge.enabled: "false"
  timeout.hard.reconciliation: 0s
  timeout.reconciliation: 180s
  url: https://argocd.upikoth.dev
