apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: alloy-daemon-set
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: grafana-alloy
  template:
    metadata:
      labels:
        app.kubernetes.io/name: grafana-alloy
    spec:
      serviceAccountName: alloy-service-account
      containers:
        - name: alloy
          image: grafana/alloy:1.8.0
          args:
            - run
            - /etc/agent/config.alloy
          ports:
            - containerPort: 3100
              name: http
          volumeMounts:
            - name: alloy-config
              mountPath: /etc/agent
            - name: varlog
              mountPath: /var/log
            - name: podlogs
              mountPath: /var/log/pods
              readOnly: true
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              cpu: 100m
              memory: 256Mi
      volumes:
        - name: alloy-config
          configMap:
            name: alloy-config
        - name: varlog
          hostPath:
            path: /var/log
        - name: podlogs
          hostPath:
            path: /var/log/pods
