apiVersion: v1
kind: ConfigMap
metadata:
  name: alloy-config
data:
  config.alloy: |-
    logging {
      level = "debug"
    }

    discovery.kubernetes "k3s" {
      role = "pod"
    }

    discovery.relabel "k3s" {
      targets = discovery.kubernetes.k3s.targets

      rule {
        source_labels = ["__meta_kubernetes_pod_uid", "__meta_kubernetes_pod_container_name"]
        target_label  = "__path__"
        separator     = "/"
        replacement   = "/var/log/pods/*$1/*.log"
      }

      rule {
        source_labels = ["__meta_kubernetes_namespace", "__meta_kubernetes_pod_label_app_kubernetes_io_name"]
        target_label  = "service"
        separator     = "/"
      }
    }

    local.file_match "pods" {
      path_targets = discovery.relabel.k3s.output
    }

    loki.source.file "log_scrape" {
      targets    = local.file_match.pods.targets
      forward_to = [loki.write.grafana_loki.receiver]
      tail_from_end = true
    }

    loki.write "grafana_loki" {
      endpoint {
        url = "http://loki-service.loki.svc.cluster.local:3100/loki/api/v1/push"
      }
    }
