apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: alloy
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: grafana-alloy
      app.kubernetes.io/component: agent
  template:
    metadata:
      labels:
        app.kubernetes.io/name: grafana-alloy
        app.kubernetes.io/component: agent
    spec:
      serviceAccountName: alloy
      containers:
        - name: alloy
          image: grafana/agent:latest
          args:
            - -config.file=/etc/agent/config.yaml
          ports:
            - containerPort: 3100
              name: http
          volumeMounts:
            - name: alloy-config
              mountPath: /etc/agent
            - name: varlog
              mountPath: /var/log
            - name: podlogs
              mountPath: /var/log/pods
              readOnly: true
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              cpu: 100m
              memory: 256Mi
      volumes:
        - name: alloy-config
          configMap:
            name: alloy-config
        - name: varlog
          hostPath:
            path: /var/log
        - name: podlogs
          hostPath:
            path: /var/log/pods
