apiVersion: v1
kind: ConfigMap
metadata:
  name: alloy-config
data:
  config.alloy: |-
    logging {
      level = "debug"
    }

    local.file_match "local_files" {
      targets = [{"__path__" = "/var/log/pods/*/*/*.log"}]
      sync_period = "5s"
    }

    loki.source.file "log_scrape" {
      targets    = local.file_match.local_files.targets
      forward_to = [loki.process.filter_logs.receiver]
      tail_from_end = true
    }

    loki.process "filter_logs" {
      stage.drop {
          source = ""
          expression  = ".*Connection closed by authenticating user root"
          drop_counter_reason = "noisy"
        }
      forward_to = [loki.write.grafana_loki.receiver]
    }

    loki.write "grafana_loki" {
      endpoint {
        url = "http://loki.loki.svc.cluster.local:3100/loki/api/v1/push"
      }
    }
