apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: grafana-alloy

resources:
  - alloy-config.yaml
  - alloy-daemonset.yaml
  - alloy-serviceaccount.yaml

commonLabels:
  app.kubernetes.io/part-of: observability
  app.kubernetes.io/name: grafana-alloy
  app.kubernetes.io/managed-by: kustomize
